#+title: CSS Vars & Design Token


* CssVars Documentation

CssVars simplifies theme management in React applications by leveraging CSS variables and providing hooks for theme customization. By following the provided guidelines, you can easily integrate design tokens and themes into your components for consistent styling.

** Introduction
CssVars is a TypeScript library designed to manage design tokens and themes using CSS variables in React applications. This documentation provides an overview of how to use CssVars in your projects.

** Installation
To use CssVars in your project, you need to install the following dependencies:

- React
- react-dom

Ensure that you have these dependencies included in your project.


** Usage
1. **CssVarsProvider**
   - The `CssVarsProvider` component is used to provide themes and design tokens to the components within its subtree.
   - It accepts the following props:
     - `themes`: An object containing theme configurations, where each key represents a theme name and the value is a DesignToken object.
     - `style` (optional): Additional CSS styles to apply to the root element.

2. **useDesignToken**
   - Custom hook to access design tokens from the context.
   - Should be used within a component wrapped by `CssVarsProvider`.

3. **useCssTheme**
   - Custom hook to manage themes and toggle between them.
   - Should be used within a component wrapped by `CssVarsProvider`.

4. **toCssVars**
   - Utility function to convert DesignToken objects into CSS variable format.

** Example 1: Simple Usage
Here is a simple example demonstrating the usage of CssVars with basic theming:

#+BEGIN_SRC html
<!doctype html>
<html lang="en">
  <head>
    <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
    <script src="/node_modules/react/umd/react.production.min.js"></script>
    <script src="/node_modules/react-dom/umd/react-dom.production.min.js"></script>
    <script src="/dist/bundle.js"></script>
    <style>
      * {
        background-color: var(--primary);
        color: var(--secondary);
      }
    </style>
  </head>
  <body>
    <div id="root"></div>
    <script type="text/babel">
      const { useCssTheme } = CssVars;
      function App() {
        const { toggle } = useCssTheme();
        return (
          <div>
            <h1>CssVars &amp; Design Token</h1>
            <button onClick={toggle}>Toggle Theme</button>
          </div>
        );
      }
      ReactDOM.createRoot(document.getElementById('root')).render(
        <CssVars.CssVarsProvider
          themes={{
            light: { primary: '#333', secondary: '#666' },
            dark: { primary: '#fff', secondary: '#ccc' },
          }}
        >
          <App />
        </CssVars.CssVarsProvider>,
      );
    </script>
  </body>
</html>
#+END_SRC

** Example 2: Nested DesignToken Usage
Here is an example demonstrating the nested nature of DesignToken for more complex theming:

#+BEGIN_SRC html
<!doctype html>
<html lang="en">
  <head>
    <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
    <script src="/node_modules/react/umd/react.production.min.js"></script>
    <script src="/node_modules/react-dom/umd/react-dom.production.min.js"></script>
    <script src="/dist/bundle.js"></script>
    <style>
      body {
        margin: var(--layout-margin, 20px);
        background-color: var(--color-bg, #f0f0f0);
        color: var(--color-fg, #333);
      }
    </style>
  </head>
  <body>
    <div id="root"></div>
    <script type="text/babel">
      const { useCssTheme } = CssVars;
      function NestedThemeComponent() {
        const { theme, toggle } = useCssTheme();

        return (
          <div>
            <h1>CssVars Nested Theme Example</h1>
            <p>Current Theme: {theme}</p>
            <button onClick={toggle}>Toggle Theme</button>
          </div>
        );
      }
      ReactDOM.createRoot(document.getElementById('root')).render(
        <CssVars.CssVarsProvider
          themes={{
            light: {
              color: { bg: '#fff', fg: '#333' },
              layout: { margin: 10 },
            },
            dark: {
              color: { bg: '#333', fg: '#fff' },
              layout: { margin: 20 },
            },
          }}
        >
          <NestedThemeComponent />
        </CssVars.CssVarsProvider>,
      );
    </script>
  </body>
</html>
#+END_SRC



#+BEGIN_SRC sh :exports results :results verbatim
cd .. && npm run test:coverage 2>&1
#+END_SRC

#+BEGIN_SRC emacs-lisp :results silent :exports none
;; To Build documentation, evaluate this block with
;; Ctrl+c Ctrl+C
(org-export-to-file 'md "../README.md")
#+END_SRC
